name: Generate SBOM
description: Generates CycloneDX SBOM for Node.js project
inputs:
  working-directory:
    description: "The directory where package.json is located"
    required: false
    default: "."
  output-file:
    description: "Output filename for the SBOM"
    required: false
    default: "sbom.json"

runs:
  using: composite
  steps:
    - name: Install CycloneDX CLI
      run: npm install -g @cyclonedx/cyclonedx-npm
      shell: bash

    - name: Generate SBOM
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cyclonedx-npm --output-file ${{ inputs.output-file }}
        echo "SBOM generated at ${{ inputs.output-file }}"

    - name: Validate SBOM
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ ! -f "${{ inputs.output-file }}" ]; then
          echo "Error: SBOM file not found"
          exit 1
        fi
        
        echo "✓ SBOM file validated: ${{ inputs.output-file }}"
        
        if command -v jq &> /dev/null; then
          echo "Components: $(jq '.components | length' ${{ inputs.output-file }})"
        fi